### ISSUE TITLE
Some Youtube URL aren't embedding

### ISSUE THREAD

**Issue by olloff** [eight04/Embed-Me#1]
At first, hi. I need to thank you for your awesome userscript, i used it to charge up web-based IM and it works awesome. But there is a problem, which I can't solve by myself, so I decide to ask your opinion on it.

You probably aware, that certain Youtube URLs don't match regex */youtube\.com\/watch\?v=([^&]+)/i*, e.g.:

    https://www.youtube.com/watch?t=1&v=1U1RY4PM6h0
    https://www.youtube.com/watch?feature=embed&v=gH7dMBcg-gE
    https://www.youtube.com/embed/b0QQspMiRdU
    https://www.youtube.com/v/98A8aX8oqgQ

In most cases its not a problem and needs only few changes to the regex to deal with. 

But there is another case which passes regex, is valid Youtube URL and works fine with GM_xmlhttpRequest. No errors or warnings present:

    https://www.youtube.com/watch?v=tGiKYlN0pDM

Though there is only one known case, I thought it need to be studied. If you need some additional info, feel free to ask.

**Comment by eight04** [comment]
I'll fix this later.
