### ISSUE TITLE
Can this be used at same time with 'No Embed Youtube'?

### ISSUE THREAD

**Issue by realAzazello** [eight04/Embed-Me#10]
Hello eight, I've been using your fabulous [No Embed Youtube](https://greasyfork.org/en/scripts/1590) since maybe day-one! I'm curious--is it possible to use Embed-Me at the same time? The reason is, I use [Youtube Link Title](https://web.archive.org/web/20190614231337/https://greasyfork.org/en/scripts/413-youtube-link-title) and [Youtube Peek Preview](https://greasyfork.org/scripts/370755) thus for obvious reasons don't want yt-vids embedded.

(Long-view: maybe a configurable method to en/disable Embed-Me for various sites e.g. I prefer no-embedding on e.g. Vimeo and Dailymotion re:[Youtube Link Title])

**Comment by eight04** [comment]
You can disable YouTube module in embed-me options.

**Comment by realAzazello** [comment]
Thank you! I see the Options also allows to exclude urls.
