### ISSUE TITLE
Should it be disabled on Github?

### ISSUE THREAD

**Issue by realAzazello** [eight04/Embed-Me#12]
(Might be related to https://github.com/eight04/Embed-Me/issues/11)

Just discovered why these...
![Capture-02](https://github.com/eight04/Embed-Me/assets/86322218/b82b44b3-c049-4891-85f0-2c9d8279e6ef)
were appearing like this...
![Capture-01](https://github.com/eight04/Embed-Me/assets/86322218/fb4d8d76-1613-491b-869f-f7fdf6d435f4)

Are there any use-cases where embedding would be useful on this site?

**Comment by eight04** [comment]
This script is useful on sites that don't support inline images e.g. some plain text based forum.

It is not really useful on Github.
