### ISSUE TITLE
(Perhaps!) support for news.ycombinator.com

### ISSUE THREAD

**Issue by realAzazello** [eight04/Embed-Me#14]
More a '_think about it_' than an actual request...

On 'Hacker News' this is how a youtube link looks with script enabled:
![Capture-05](https://github.com/eight04/Embed-Me/assets/86322218/92576dff-f584-4300-b6cc-fcff80956670)

https://news.ycombinator.com/item?id=39501616

Would be a nice-to-have to support HN.

Also, I would luv-luv-luv if Embed Me could work with [Youtube Link Title](https://web.archive.org/web/20190614231337/https://greasyfork.org/en/scripts/413-youtube-link-title) and [Youtube Peek Preview](https://greasyfork.org/scripts/370755), such that the original link would not be replaced by the embed - but maintained; that way we can get the benefits of those scripts :
![Capture-06](https://github.com/eight04/Embed-Me/assets/86322218/0130c423-ed0d-4abd-a887-c677027cae10)

the Embed Me embed could appear below the link.

**Comment by eight04** [comment]
The main problem is how to find the correct position to insert the video, and the method has to work on all websites.

Currently, the script puts the video inside the link, replacing link content. With this approach, it still often breaks the layout of the  website.
