### ISSUE TITLE
Youtube Embdding inside comments

### ISSUE THREAD

**Issue by neoOpus** [eight04/Embed-Me#5]
There is an annoying issue, that consists of embedding the videos in youtube comments for no obvious reason... so the comment section is a sort of duplicated videos of the main video we are watching which make the page heavy on resources obviously but also make the comments hard to read...

I don't know if exclusion can fix that but I tried and I didn't succeed in fixing it.

**Comment by eight04** [comment]
Can you link an example?

**Comment by neoOpus** [comment]
I fixed this by adding this exclusion to TamperMonkey 

/(^[^:\/#\?]*:\/\/([^#\?\/]*\.)?www\.youtube\.com(:[0-9]{1,5})?\/.*$)/

**Comment by adriangrantdotorg** [comment]
> I fixed this by adding this exclusion to TamperMonkey
> 
> /(^[^:\/#\?]_://([^#\?\/]_.)?www.youtube.com(:[0-9]{1,5})?/.*$)/

Hi @neoOpus  - when you get a chance can you share where you added this exclusion? I added it in TamperMonkey 'settings' area but the issue still remains.
![screenshot_106](https://user-images.githubusercontent.com/1000506/144663974-473e706e-89f3-4e5f-8733-89a8885951de.png)

**Comment by neoOpus** [comment]
Hi Adrian,

I'm sorry but I didn't use this script for a while, so my solution doesn't fix the issue anymore, I tinkered a bit  since you asked, but I have to come up with a solution because the dev seems to be that he isn't working on this one anymore

**Comment by adriangrantdotorg** [comment]
No worries - thanks for the reply & details @neoOpus!

**Comment by eight04** [comment]
With Tampermonkey, Instead of adding exclude rules manually, [you can configure it from the popup](https://www.reddit.com/r/userscripts/comments/ab7wyi/how_to_add_a_site_to_exclusion_for_a_script_in/).

**Comment by adriangrantdotorg** [comment]
> With Tampermonkey, Instead of adding exclude rules manually, [you can configure it from the popup](https://www.reddit.com/r/userscripts/comments/ab7wyi/how_to_add_a_site_to_exclusion_for_a_script_in/).

Perfect - this solved the issue - thank you for this amazing script!
